### ISSUE TITLE
qa-task-general

### ISSUE THREAD

**Issue by zainasaadeddin** [OppoTrain/Testing-Sardiya#7]

**Comment by raghad-y-suwan** [comment]
![Image](https://github.com/user-attachments/assets/a924357c-441e-45a4-89be-532a1c12c50b)
عدم تحميل الاسم وبعد فترة تم تغييره على كبسة السيرتش

**Comment by raghad-y-suwan** [comment]
![Image](https://github.com/user-attachments/assets/a7bc3185-a374-4bc0-bf5f-9c05665a0f9d)
لقد قمت بكتابة israel في السيرتش 
فقام بتغيير الكلمة في السيرتش بار ولم يقم بتغيير الكلمة في جوجل 

![Image](https://github.com/user-attachments/assets/887ec768-69ac-4f08-9e14-2550e6acf405)

**Comment by raghad-y-suwan** [comment]
![Image](https://github.com/user-attachments/assets/dcd031a7-0b15-4e29-845d-c9566e46808a)
 عند الضغط على تعديل واضافة كلمات جديدة ثم الضغط على كبسة التفعيل يظهر هذا الخطا الفظيع

**Comment by ReemaKusa** [comment]
![Image](https://github.com/user-attachments/assets/95f07d9f-4046-4dbe-b746-cd3e49ac26ff)
![Image](https://github.com/user-attachments/assets/1d59cfcc-3d18-491b-8676-530bccae8a15)
UX-User experience:
بالبنسبة للمستخدم يجب ان تكون كبسة التفعيل باللون الابيض وعند تفعيلها تتحول الى الاخضر وليس العكس

**Comment by ReemaKusa** [comment]
![Image](https://github.com/user-attachments/assets/2cc9cd2e-b473-4ab4-8967-4c1b9c74e17c)
![Image](https://github.com/user-attachments/assets/6742def3-c845-4ee3-89d7-cc1ecf2736b9)

UX-User experience: 
(الكلمة) (الاصل)
.(تعبير غير واضح للمستخدم الي ما بعرف كفاية عن الاكستنشن او لشو ممكن يستخدمها, ممكن تعديلها ل (اسم المكان المحتل) /  (الاسم الاصلي للمكان
(Word) (Replacement)
to (Name of the occupied place ) / (The original name of the place).

**Comment by ReemaKusa** [comment]
![Image](https://github.com/user-attachments/assets/e8f2748e-b591-45d8-b4bf-5dd0e436a3db)
![Image](https://github.com/user-attachments/assets/61ba2f6d-fc70-472d-a563-8809b8c6b0b7)

UX-User experience:
(Submit) -> Save Word (More descriptive and action-specific).
(Cancel) -> Go Back or Clear (Better reflects the user's intended action).

(إرسال) -> حفظ الكلمة (اوضح أكثر وصفية ومخصصة للإجراء).
(إلغاء) -> العودة أو المسح (يعكس بشكل أفضل الإجراء المقصود للمستخدم).

**Comment by raghad-y-suwan** [comment]
notes that theres alot of comments in the code , it should be removed
